language: go
go_import_path: github.com/Viva-Victoria/bear-jwt

env:
  global:
    - GO111MODULE=on

go:
  - stable

before_install:
  - go version
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.0

script:
  - golangci-lint run
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./

after_success:
  - bash <(curl -s https://codecov.io/bash)
